version: '3'

services:

  supremm:
    image: cisl-repo/xdmod_cisl_supremm:${TAG_supremm}
    volumes:
      - ${VOLMAP_SECRETS}:/run/secrets
      - ${VOLMAP_LOGS}:/var/log
      - ${VOLMAP_APP_DATA}:/var/xdmod
    networks:
      - default
      - mail
    env_file:
      - deploy.env

  mongodb:
    image: cisl-repo/xdmod_cisl_mongodb:${TAG_mongodb}
    volumes:
      - ${VOLMAP_SECRETS}:/run/secrets
      - ${VOLMAP_LOGS}:/var/log
      - ${VOLMAP_MONGODB_DATA}:/data/db
    ports:
      - ${PORTMAP_MONGODB}:27017
    networks:
      - default
    env_file:
      - deploy.env

networks:
  default:
  mail:
    external:
      name: mail

