version: '3'

services:

  logingest:
    image: cisl-repo/xdmod_cisl_logingest:${TAG_logingest}
    volumes:
      - ${VOLMAP_SECRETS}:/run/secrets
      - ${VOLMAP_LOGS}:/var/log
      - ${VOLMAP_APP_DATA}:/var/xdmod
    networks:
      - default
      - mail
    env_file:
      - deploy.env

  webapp:
    image: cisl-repo/xdmod_cisl_webapp:${TAG_webapp}
    volumes:
      - ${VOLMAP_SECRETS}:/run/secrets
      - ${VOLMAP_LOGS}:/var/log
    ports:
      - ${PORTMAP_WEBAPP}:443
    networks:
      - default
      - mail
    env_file:
      - deploy.env

  mongodb:
    image: cisl-repo/xdmod_cisl_mongodb:${TAG_mongodb}
    volumes:
      - ${VOLMAP_SECRETS}:/run/secrets
      - ${VOLMAP_LOGS}:/var/log
      - ${VOLMAP_MONGODB_DATA}:/data/db
    ports:
      - ${PORTMAP_MONGODB}:27017
    networks:
      - default
    env_file:
      - deploy.env

#  db:
#    image: cisl-repo/xdmod_cisl_db:${TAG_db}
#    volumes:
#      - ${VOLMAP_SECRETS}:/run/secrets
#      - ${VOLMAP_LOGS}:/var/log
#      - ${VOLMAP_DB_DATA}:/var/lib/mysql
#    ports:
#      - ${PORTMAP_DB}:3306
#    env_file:
#      - deploy.env
#    environment:
#      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql-root-password

networks:
  default:
  mail:
    external:
      name: mail

